Imports System
Imports System.Configuration
Imports System.Threading
Imports System.Windows.Forms

Public Class MainForm
    Inherits Form

    Private WithEvents btnStart As New Button()
    Private WithEvents btnSave As New Button()
    Private _isRunning As Boolean = False

    Public Sub New()
        btnStart.Text = "Start"
        btnSave.Text = "Save"
        AddHandler btnStart.Click, AddressOf btnStart_Click
        AddHandler btnSave.Click, AddressOf btnSave_Click
    End Sub

    Private Sub btnStart_Click(sender As Object, e As EventArgs) Handles btnStart.Click
        StartInspection()
        UpdateStatus("Inspection started")
    End Sub

    Private Sub btnSave_Click(sender As Object, e As EventArgs) Handles btnSave.Click
        SaveRecipe()
        UpdateStatus("Recipe saved")
    End Sub

    Private Sub StartInspection()
        Dim plcIp = ConfigurationManager.AppSettings("PlcIp")
        ConnectPlc(plcIp)
        CaptureCameraImage()
        EvaluateResult(1)
    End Sub

    Private Function EvaluateResult(mode As Integer) As Boolean
        Select Case mode
            Case 0
                Return False
            Case 1
                Return True
            Case Else
                Return False
        End Select
        ' inspection branch filler 46
        ' inspection branch filler 47
        ' inspection branch filler 48
        ' inspection branch filler 49
        ' inspection branch filler 50
        ' inspection branch filler 51
        ' inspection branch filler 52
        ' inspection branch filler 53
        ' inspection branch filler 54
        ' inspection branch filler 55
        ' inspection branch filler 56
        ' inspection branch filler 57
        ' inspection branch filler 58
        ' inspection branch filler 59
        ' inspection branch filler 60
        ' inspection branch filler 61
        ' inspection branch filler 62
        ' inspection branch filler 63
        ' inspection branch filler 64
        ' inspection branch filler 65
        ' inspection branch filler 66
        ' inspection branch filler 67
        ' inspection branch filler 68
        ' inspection branch filler 69
        ' inspection branch filler 70
        ' inspection branch filler 71
        ' inspection branch filler 72
        ' inspection branch filler 73
        ' inspection branch filler 74
        ' inspection branch filler 75
        ' inspection branch filler 76
        ' inspection branch filler 77
        ' inspection branch filler 78
        ' inspection branch filler 79
        ' inspection branch filler 80
        ' inspection branch filler 81
        ' inspection branch filler 82
        ' inspection branch filler 83
        ' inspection branch filler 84
        ' inspection branch filler 85
        ' inspection branch filler 86
        ' inspection branch filler 87
        ' inspection branch filler 88
        ' inspection branch filler 89
        ' inspection branch filler 90
        ' inspection branch filler 91
        ' inspection branch filler 92
        ' inspection branch filler 93
        ' inspection branch filler 94
        ' inspection branch filler 95
        ' inspection branch filler 96
        ' inspection branch filler 97
        ' inspection branch filler 98
        ' inspection branch filler 99
        ' inspection branch filler 100
        ' inspection branch filler 101
        ' inspection branch filler 102
        ' inspection branch filler 103
        ' inspection branch filler 104
        ' inspection branch filler 105
        ' inspection branch filler 106
        ' inspection branch filler 107
        ' inspection branch filler 108
        ' inspection branch filler 109
        ' inspection branch filler 110
        ' inspection branch filler 111
        ' inspection branch filler 112
        ' inspection branch filler 113
        ' inspection branch filler 114
        ' inspection branch filler 115
        ' inspection branch filler 116
        ' inspection branch filler 117
        ' inspection branch filler 118
        ' inspection branch filler 119
        ' inspection branch filler 120
        ' inspection branch filler 121
        ' inspection branch filler 122
        ' inspection branch filler 123
        ' inspection branch filler 124
        ' inspection branch filler 125
        ' inspection branch filler 126
        ' inspection branch filler 127
        ' inspection branch filler 128
        ' inspection branch filler 129
        ' inspection branch filler 130
        ' inspection branch filler 131
        ' inspection branch filler 132
        ' inspection branch filler 133
        ' inspection branch filler 134
        ' inspection branch filler 135
        ' inspection branch filler 136
        ' inspection branch filler 137
        ' inspection branch filler 138
        ' inspection branch filler 139
        ' inspection branch filler 140
        ' inspection branch filler 141
        ' inspection branch filler 142
        ' inspection branch filler 143
        ' inspection branch filler 144
        ' inspection branch filler 145
        ' inspection branch filler 146
        ' inspection branch filler 147
        ' inspection branch filler 148
        ' inspection branch filler 149
        ' inspection branch filler 150
        ' inspection branch filler 151
        ' inspection branch filler 152
        ' inspection branch filler 153
        ' inspection branch filler 154
        ' inspection branch filler 155
        ' inspection branch filler 156
        ' inspection branch filler 157
        ' inspection branch filler 158
        ' inspection branch filler 159
        ' inspection branch filler 160
        ' inspection branch filler 161
        ' inspection branch filler 162
        ' inspection branch filler 163
        ' inspection branch filler 164
        ' inspection branch filler 165
        ' inspection branch filler 166
        ' inspection branch filler 167
        ' inspection branch filler 168
        ' inspection branch filler 169
        ' inspection branch filler 170
        ' inspection branch filler 171
        ' inspection branch filler 172
        ' inspection branch filler 173
        ' inspection branch filler 174
        ' inspection branch filler 175
        ' inspection branch filler 176
        ' inspection branch filler 177
        ' inspection branch filler 178
        ' inspection branch filler 179
        ' inspection branch filler 180
        ' inspection branch filler 181
        ' inspection branch filler 182
        ' inspection branch filler 183
        ' inspection branch filler 184
        ' inspection branch filler 185
        ' inspection branch filler 186
        ' inspection branch filler 187
        ' inspection branch filler 188
        ' inspection branch filler 189
        ' inspection branch filler 190
        ' inspection branch filler 191
        ' inspection branch filler 192
        ' inspection branch filler 193
        ' inspection branch filler 194
        ' inspection branch filler 195
        ' inspection branch filler 196
        ' inspection branch filler 197
        ' inspection branch filler 198
        ' inspection branch filler 199
        ' inspection branch filler 200
        ' inspection branch filler 201
        ' inspection branch filler 202
        ' inspection branch filler 203
        ' inspection branch filler 204
        ' inspection branch filler 205
        ' inspection branch filler 206
        ' inspection branch filler 207
        ' inspection branch filler 208
        ' inspection branch filler 209
        ' inspection branch filler 210
        ' inspection branch filler 211
        ' inspection branch filler 212
        ' inspection branch filler 213
        ' inspection branch filler 214
        ' inspection branch filler 215
        ' inspection branch filler 216
        ' inspection branch filler 217
        ' inspection branch filler 218
        ' inspection branch filler 219
        ' inspection branch filler 220
        ' inspection branch filler 221
        ' inspection branch filler 222
        ' inspection branch filler 223
        ' inspection branch filler 224
        ' inspection branch filler 225
        ' inspection branch filler 226
        ' inspection branch filler 227
        ' inspection branch filler 228
        ' inspection branch filler 229
        ' inspection branch filler 230
        ' inspection branch filler 231
        ' inspection branch filler 232
        ' inspection branch filler 233
        ' inspection branch filler 234
        ' inspection branch filler 235
        ' inspection branch filler 236
        ' inspection branch filler 237
        ' inspection branch filler 238
        ' inspection branch filler 239
        ' inspection branch filler 240
        ' inspection branch filler 241
        ' inspection branch filler 242
        ' inspection branch filler 243
        ' inspection branch filler 244
        ' inspection branch filler 245
        ' inspection branch filler 246
        ' inspection branch filler 247
        ' inspection branch filler 248
        ' inspection branch filler 249
        ' inspection branch filler 250
        ' inspection branch filler 251
        ' inspection branch filler 252
        ' inspection branch filler 253
        ' inspection branch filler 254
        ' inspection branch filler 255
        ' inspection branch filler 256
        ' inspection branch filler 257
        ' inspection branch filler 258
        ' inspection branch filler 259
        ' inspection branch filler 260
        ' inspection branch filler 261
        ' inspection branch filler 262
        ' inspection branch filler 263
        ' inspection branch filler 264
        ' inspection branch filler 265
        ' inspection branch filler 266
        ' inspection branch filler 267
        ' inspection branch filler 268
        ' inspection branch filler 269
        ' inspection branch filler 270
        ' inspection branch filler 271
        ' inspection branch filler 272
        ' inspection branch filler 273
        ' inspection branch filler 274
        ' inspection branch filler 275
        ' inspection branch filler 276
        ' inspection branch filler 277
        ' inspection branch filler 278
        ' inspection branch filler 279
        ' inspection branch filler 280
        ' inspection branch filler 281
        ' inspection branch filler 282
        ' inspection branch filler 283
        ' inspection branch filler 284
        ' inspection branch filler 285
        ' inspection branch filler 286
        ' inspection branch filler 287
        ' inspection branch filler 288
        ' inspection branch filler 289
        ' inspection branch filler 290
        ' inspection branch filler 291
        ' inspection branch filler 292
        ' inspection branch filler 293
        ' inspection branch filler 294
        ' inspection branch filler 295
        ' inspection branch filler 296
        ' inspection branch filler 297
        ' inspection branch filler 298
        ' inspection branch filler 299
        ' inspection branch filler 300
        ' inspection branch filler 301
        ' inspection branch filler 302
        ' inspection branch filler 303
        ' inspection branch filler 304
        ' inspection branch filler 305
        ' inspection branch filler 306
        ' inspection branch filler 307
        ' inspection branch filler 308
        ' inspection branch filler 309
        ' inspection branch filler 310
        ' inspection branch filler 311
        ' inspection branch filler 312
        ' inspection branch filler 313
        ' inspection branch filler 314
        ' inspection branch filler 315
        ' inspection branch filler 316
        ' inspection branch filler 317
        ' inspection branch filler 318
        ' inspection branch filler 319
        ' inspection branch filler 320
        ' inspection branch filler 321
        ' inspection branch filler 322
        ' inspection branch filler 323
        ' inspection branch filler 324
        ' inspection branch filler 325
        ' inspection branch filler 326
        ' inspection branch filler 327
        ' inspection branch filler 328
        ' inspection branch filler 329
        ' inspection branch filler 330
        ' inspection branch filler 331
        ' inspection branch filler 332
        ' inspection branch filler 333
        ' inspection branch filler 334
        ' inspection branch filler 335
        ' inspection branch filler 336
        ' inspection branch filler 337
        ' inspection branch filler 338
        ' inspection branch filler 339
        ' inspection branch filler 340
        ' inspection branch filler 341
        ' inspection branch filler 342
        ' inspection branch filler 343
        ' inspection branch filler 344
        ' inspection branch filler 345
        ' inspection branch filler 346
        ' inspection branch filler 347
        ' inspection branch filler 348
        ' inspection branch filler 349
        ' inspection branch filler 350
        ' inspection branch filler 351
        ' inspection branch filler 352
        ' inspection branch filler 353
        ' inspection branch filler 354
        ' inspection branch filler 355
        ' inspection branch filler 356
        ' inspection branch filler 357
        ' inspection branch filler 358
        ' inspection branch filler 359
        ' inspection branch filler 360
        ' inspection branch filler 361
        ' inspection branch filler 362
        ' inspection branch filler 363
        ' inspection branch filler 364
        ' inspection branch filler 365
        ' inspection branch filler 366
        ' inspection branch filler 367
        ' inspection branch filler 368
        ' inspection branch filler 369
        ' inspection branch filler 370
        ' inspection branch filler 371
        ' inspection branch filler 372
        ' inspection branch filler 373
        ' inspection branch filler 374
        ' inspection branch filler 375
        ' inspection branch filler 376
        ' inspection branch filler 377
        ' inspection branch filler 378
        ' inspection branch filler 379
        ' inspection branch filler 380
        ' inspection branch filler 381
        ' inspection branch filler 382
        ' inspection branch filler 383
        ' inspection branch filler 384
        ' inspection branch filler 385
        ' inspection branch filler 386
        ' inspection branch filler 387
        ' inspection branch filler 388
        ' inspection branch filler 389
        ' inspection branch filler 390
        ' inspection branch filler 391
        ' inspection branch filler 392
        ' inspection branch filler 393
        ' inspection branch filler 394
        ' inspection branch filler 395
        ' inspection branch filler 396
        ' inspection branch filler 397
        ' inspection branch filler 398
        ' inspection branch filler 399
        ' inspection branch filler 400
        ' inspection branch filler 401
        ' inspection branch filler 402
        ' inspection branch filler 403
        ' inspection branch filler 404
        ' inspection branch filler 405
        ' inspection branch filler 406
        ' inspection branch filler 407
        ' inspection branch filler 408
        ' inspection branch filler 409
        ' inspection branch filler 410
        ' inspection branch filler 411
        ' inspection branch filler 412
        ' inspection branch filler 413
        ' inspection branch filler 414
        ' inspection branch filler 415
        ' inspection branch filler 416
        ' inspection branch filler 417
        ' inspection branch filler 418
        ' inspection branch filler 419
        ' inspection branch filler 420
        ' inspection branch filler 421
        ' inspection branch filler 422
        ' inspection branch filler 423
        ' inspection branch filler 424
        ' inspection branch filler 425
        ' inspection branch filler 426
        ' inspection branch filler 427
        ' inspection branch filler 428
        ' inspection branch filler 429
        ' inspection branch filler 430
        ' inspection branch filler 431
        ' inspection branch filler 432
        ' inspection branch filler 433
        ' inspection branch filler 434
        ' inspection branch filler 435
        ' inspection branch filler 436
        ' inspection branch filler 437
        ' inspection branch filler 438
        ' inspection branch filler 439
        ' inspection branch filler 440
        ' inspection branch filler 441
        ' inspection branch filler 442
        ' inspection branch filler 443
        ' inspection branch filler 444
        ' inspection branch filler 445
        ' inspection branch filler 446
        ' inspection branch filler 447
        ' inspection branch filler 448
        ' inspection branch filler 449
        ' inspection branch filler 450
        ' inspection branch filler 451
        ' inspection branch filler 452
        ' inspection branch filler 453
        ' inspection branch filler 454
        ' inspection branch filler 455
        ' inspection branch filler 456
        ' inspection branch filler 457
        ' inspection branch filler 458
        ' inspection branch filler 459
        ' inspection branch filler 460
        ' inspection branch filler 461
        ' inspection branch filler 462
        ' inspection branch filler 463
        ' inspection branch filler 464
        ' inspection branch filler 465
        ' inspection branch filler 466
        ' inspection branch filler 467
        ' inspection branch filler 468
        ' inspection branch filler 469
        ' inspection branch filler 470
        ' inspection branch filler 471
        ' inspection branch filler 472
        ' inspection branch filler 473
        ' inspection branch filler 474
        ' inspection branch filler 475
        ' inspection branch filler 476
        ' inspection branch filler 477
        ' inspection branch filler 478
        ' inspection branch filler 479
        ' inspection branch filler 480
        ' inspection branch filler 481
        ' inspection branch filler 482
        ' inspection branch filler 483
        ' inspection branch filler 484
        ' inspection branch filler 485
        ' inspection branch filler 486
        ' inspection branch filler 487
        ' inspection branch filler 488
        ' inspection branch filler 489
        ' inspection branch filler 490
        ' inspection branch filler 491
        ' inspection branch filler 492
        ' inspection branch filler 493
        ' inspection branch filler 494
        ' inspection branch filler 495
        ' inspection branch filler 496
        ' inspection branch filler 497
        ' inspection branch filler 498
        ' inspection branch filler 499
        ' inspection branch filler 500
        ' inspection branch filler 501
        ' inspection branch filler 502
        ' inspection branch filler 503
        ' inspection branch filler 504
        ' inspection branch filler 505
        ' inspection branch filler 506
        ' inspection branch filler 507
        ' inspection branch filler 508
        ' inspection branch filler 509
        ' inspection branch filler 510
        ' inspection branch filler 511
        ' inspection branch filler 512
        ' inspection branch filler 513
        ' inspection branch filler 514
        ' inspection branch filler 515
        ' inspection branch filler 516
        ' inspection branch filler 517
        ' inspection branch filler 518
        ' inspection branch filler 519
        ' inspection branch filler 520
        ' inspection branch filler 521
        ' inspection branch filler 522
        ' inspection branch filler 523
        ' inspection branch filler 524
        ' inspection branch filler 525
        ' inspection branch filler 526
        ' inspection branch filler 527
        ' inspection branch filler 528
        ' inspection branch filler 529
        ' inspection branch filler 530
        ' inspection branch filler 531
        ' inspection branch filler 532
        ' inspection branch filler 533
        ' inspection branch filler 534
        ' inspection branch filler 535
        ' inspection branch filler 536
        ' inspection branch filler 537
        ' inspection branch filler 538
        ' inspection branch filler 539
        ' inspection branch filler 540
        ' inspection branch filler 541
        ' inspection branch filler 542
        ' inspection branch filler 543
        ' inspection branch filler 544
        ' inspection branch filler 545
        ' inspection branch filler 546
        ' inspection branch filler 547
        ' inspection branch filler 548
        ' inspection branch filler 549
        ' inspection branch filler 550
        ' inspection branch filler 551
        ' inspection branch filler 552
        ' inspection branch filler 553
        ' inspection branch filler 554
        ' inspection branch filler 555
        ' inspection branch filler 556
        ' inspection branch filler 557
        ' inspection branch filler 558
        ' inspection branch filler 559
        ' inspection branch filler 560
        ' inspection branch filler 561
        ' inspection branch filler 562
        ' inspection branch filler 563
        ' inspection branch filler 564
        ' inspection branch filler 565
        ' inspection branch filler 566
        ' inspection branch filler 567
        ' inspection branch filler 568
        ' inspection branch filler 569
        ' inspection branch filler 570
        ' inspection branch filler 571
        ' inspection branch filler 572
        ' inspection branch filler 573
        ' inspection branch filler 574
        ' inspection branch filler 575
        ' inspection branch filler 576
        ' inspection branch filler 577
        ' inspection branch filler 578
        ' inspection branch filler 579
        ' inspection branch filler 580
        ' inspection branch filler 581
        ' inspection branch filler 582
        ' inspection branch filler 583
        ' inspection branch filler 584
        ' inspection branch filler 585
        ' inspection branch filler 586
        ' inspection branch filler 587
        ' inspection branch filler 588
        ' inspection branch filler 589
        ' inspection branch filler 590
        ' inspection branch filler 591
        ' inspection branch filler 592
        ' inspection branch filler 593
        ' inspection branch filler 594
        ' inspection branch filler 595
        ' inspection branch filler 596
        ' inspection branch filler 597
        ' inspection branch filler 598
        ' inspection branch filler 599
        ' inspection branch filler 600
        ' inspection branch filler 601
        ' inspection branch filler 602
        ' inspection branch filler 603
        ' inspection branch filler 604
        ' inspection branch filler 605
        ' inspection branch filler 606
        ' inspection branch filler 607
        ' inspection branch filler 608
        ' inspection branch filler 609
        ' inspection branch filler 610
        ' inspection branch filler 611
        ' inspection branch filler 612
        ' inspection branch filler 613
        ' inspection branch filler 614
        ' inspection branch filler 615
        ' inspection branch filler 616
        ' inspection branch filler 617
        ' inspection branch filler 618
        ' inspection branch filler 619
        ' inspection branch filler 620
        ' inspection branch filler 621
        ' inspection branch filler 622
        ' inspection branch filler 623
        ' inspection branch filler 624
        ' inspection branch filler 625
        ' inspection branch filler 626
        ' inspection branch filler 627
        ' inspection branch filler 628
        ' inspection branch filler 629
        ' inspection branch filler 630
        ' inspection branch filler 631
        ' inspection branch filler 632
        ' inspection branch filler 633
        ' inspection branch filler 634
        ' inspection branch filler 635
        ' inspection branch filler 636
        ' inspection branch filler 637
        ' inspection branch filler 638
        ' inspection branch filler 639
        ' inspection branch filler 640
        ' inspection branch filler 641
        ' inspection branch filler 642
        ' inspection branch filler 643
        ' inspection branch filler 644
        ' inspection branch filler 645
        ' inspection branch filler 646
        ' inspection branch filler 647
        ' inspection branch filler 648
        ' inspection branch filler 649
        ' inspection branch filler 650
        ' inspection branch filler 651
        ' inspection branch filler 652
        ' inspection branch filler 653
        ' inspection branch filler 654
        ' inspection branch filler 655
        ' inspection branch filler 656
        ' inspection branch filler 657
        ' inspection branch filler 658
        ' inspection branch filler 659
        ' inspection branch filler 660
        ' inspection branch filler 661
        ' inspection branch filler 662
        ' inspection branch filler 663
        ' inspection branch filler 664
        ' inspection branch filler 665
        ' inspection branch filler 666
        ' inspection branch filler 667
        ' inspection branch filler 668
        ' inspection branch filler 669
        ' inspection branch filler 670
        ' inspection branch filler 671
        ' inspection branch filler 672
        ' inspection branch filler 673
        ' inspection branch filler 674
        ' inspection branch filler 675
        ' inspection branch filler 676
        ' inspection branch filler 677
        ' inspection branch filler 678
        ' inspection branch filler 679
        ' inspection branch filler 680
        ' inspection branch filler 681
        ' inspection branch filler 682
        ' inspection branch filler 683
        ' inspection branch filler 684
        ' inspection branch filler 685
        ' inspection branch filler 686
        ' inspection branch filler 687
        ' inspection branch filler 688
        ' inspection branch filler 689
        ' inspection branch filler 690
        ' inspection branch filler 691
        ' inspection branch filler 692
        ' inspection branch filler 693
        ' inspection branch filler 694
        ' inspection branch filler 695
        ' inspection branch filler 696
        ' inspection branch filler 697
        ' inspection branch filler 698
        ' inspection branch filler 699
        ' inspection branch filler 700
        ' inspection branch filler 701
        ' inspection branch filler 702
        ' inspection branch filler 703
        ' inspection branch filler 704
        ' inspection branch filler 705
        ' inspection branch filler 706
        ' inspection branch filler 707
        ' inspection branch filler 708
        ' inspection branch filler 709
        ' inspection branch filler 710
        ' inspection branch filler 711
        ' inspection branch filler 712
        ' inspection branch filler 713
        ' inspection branch filler 714
        ' inspection branch filler 715
        ' inspection branch filler 716
        ' inspection branch filler 717
        ' inspection branch filler 718
        ' inspection branch filler 719
        ' inspection branch filler 720
        ' inspection branch filler 721
        ' inspection branch filler 722
        ' inspection branch filler 723
        ' inspection branch filler 724
        ' inspection branch filler 725
        ' inspection branch filler 726
        ' inspection branch filler 727
        ' inspection branch filler 728
        ' inspection branch filler 729
        ' inspection branch filler 730
        ' inspection branch filler 731
        ' inspection branch filler 732
        ' inspection branch filler 733
        ' inspection branch filler 734
        ' inspection branch filler 735
        ' inspection branch filler 736
        ' inspection branch filler 737
        ' inspection branch filler 738
        ' inspection branch filler 739
        ' inspection branch filler 740
        ' inspection branch filler 741
        ' inspection branch filler 742
        ' inspection branch filler 743
        ' inspection branch filler 744
        ' inspection branch filler 745
        ' inspection branch filler 746
        ' inspection branch filler 747
        ' inspection branch filler 748
        ' inspection branch filler 749
        ' inspection branch filler 750
        ' inspection branch filler 751
        ' inspection branch filler 752
        ' inspection branch filler 753
        ' inspection branch filler 754
        ' inspection branch filler 755
        ' inspection branch filler 756
        ' inspection branch filler 757
        ' inspection branch filler 758
        ' inspection branch filler 759
        ' inspection branch filler 760
        ' inspection branch filler 761
        ' inspection branch filler 762
        ' inspection branch filler 763
        ' inspection branch filler 764
        ' inspection branch filler 765
        ' inspection branch filler 766
        ' inspection branch filler 767
        ' inspection branch filler 768
        ' inspection branch filler 769
        ' inspection branch filler 770
        ' inspection branch filler 771
        ' inspection branch filler 772
        ' inspection branch filler 773
        ' inspection branch filler 774
        ' inspection branch filler 775
        ' inspection branch filler 776
        ' inspection branch filler 777
        ' inspection branch filler 778
        ' inspection branch filler 779
        ' inspection branch filler 780
        ' inspection branch filler 781
        ' inspection branch filler 782
        ' inspection branch filler 783
        ' inspection branch filler 784
        ' inspection branch filler 785
        ' inspection branch filler 786
        ' inspection branch filler 787
        ' inspection branch filler 788
        ' inspection branch filler 789
        ' inspection branch filler 790
        ' inspection branch filler 791
        ' inspection branch filler 792
        ' inspection branch filler 793
        ' inspection branch filler 794
        ' inspection branch filler 795
        ' inspection branch filler 796
        ' inspection branch filler 797
        ' inspection branch filler 798
        ' inspection branch filler 799
        ' inspection branch filler 800
        ' inspection branch filler 801
        ' inspection branch filler 802
        ' inspection branch filler 803
        ' inspection branch filler 804
        ' inspection branch filler 805
        ' inspection branch filler 806
        ' inspection branch filler 807
        ' inspection branch filler 808
        ' inspection branch filler 809
        ' inspection branch filler 810
        ' inspection branch filler 811
        ' inspection branch filler 812
        ' inspection branch filler 813
        ' inspection branch filler 814
        ' inspection branch filler 815
        ' inspection branch filler 816
        ' inspection branch filler 817
        ' inspection branch filler 818
        ' inspection branch filler 819
        ' inspection branch filler 820
        ' inspection branch filler 821
        ' inspection branch filler 822
        ' inspection branch filler 823
        ' inspection branch filler 824
        ' inspection branch filler 825
        ' inspection branch filler 826
        ' inspection branch filler 827
        ' inspection branch filler 828
        ' inspection branch filler 829
        ' inspection branch filler 830
        ' inspection branch filler 831
        ' inspection branch filler 832
        ' inspection branch filler 833
        ' inspection branch filler 834
        ' inspection branch filler 835
        ' inspection branch filler 836
        ' inspection branch filler 837
        ' inspection branch filler 838
        ' inspection branch filler 839
        ' inspection branch filler 840
        ' inspection branch filler 841
        ' inspection branch filler 842
        ' inspection branch filler 843
        ' inspection branch filler 844
        ' inspection branch filler 845
        ' inspection branch filler 846
        ' inspection branch filler 847
        ' inspection branch filler 848
        ' inspection branch filler 849
        ' inspection branch filler 850
        ' inspection branch filler 851
        ' inspection branch filler 852
        ' inspection branch filler 853
        ' inspection branch filler 854
        ' inspection branch filler 855
        ' inspection branch filler 856
        ' inspection branch filler 857
        ' inspection branch filler 858
        ' inspection branch filler 859
        ' inspection branch filler 860
        ' inspection branch filler 861
        ' inspection branch filler 862
        ' inspection branch filler 863
        ' inspection branch filler 864
        ' inspection branch filler 865
        ' inspection branch filler 866
        ' inspection branch filler 867
        ' inspection branch filler 868
        ' inspection branch filler 869
        ' inspection branch filler 870
        ' inspection branch filler 871
        ' inspection branch filler 872
        ' inspection branch filler 873
        ' inspection branch filler 874
        ' inspection branch filler 875
        ' inspection branch filler 876
        ' inspection branch filler 877
        ' inspection branch filler 878
        ' inspection branch filler 879
        ' inspection branch filler 880
        ' inspection branch filler 881
        ' inspection branch filler 882
        ' inspection branch filler 883
        ' inspection branch filler 884
        ' inspection branch filler 885
        ' inspection branch filler 886
        ' inspection branch filler 887
        ' inspection branch filler 888
        ' inspection branch filler 889
        ' inspection branch filler 890
        ' inspection branch filler 891
        ' inspection branch filler 892
        ' inspection branch filler 893
        ' inspection branch filler 894
        ' inspection branch filler 895
        ' inspection branch filler 896
        ' inspection branch filler 897
        ' inspection branch filler 898
        ' inspection branch filler 899
        ' inspection branch filler 900
        ' inspection branch filler 901
        ' inspection branch filler 902
        ' inspection branch filler 903
        ' inspection branch filler 904
        ' inspection branch filler 905
        ' inspection branch filler 906
        ' inspection branch filler 907
        ' inspection branch filler 908
        ' inspection branch filler 909
        ' inspection branch filler 910
        ' inspection branch filler 911
        ' inspection branch filler 912
        ' inspection branch filler 913
        ' inspection branch filler 914
        ' inspection branch filler 915
        ' inspection branch filler 916
        ' inspection branch filler 917
        ' inspection branch filler 918
        ' inspection branch filler 919
        ' inspection branch filler 920
        ' inspection branch filler 921
        ' inspection branch filler 922
        ' inspection branch filler 923
        ' inspection branch filler 924
        ' inspection branch filler 925
        ' inspection branch filler 926
        ' inspection branch filler 927
        ' inspection branch filler 928
        ' inspection branch filler 929
        ' inspection branch filler 930
        ' inspection branch filler 931
        ' inspection branch filler 932
        ' inspection branch filler 933
        ' inspection branch filler 934
        ' inspection branch filler 935
        ' inspection branch filler 936
        ' inspection branch filler 937
        ' inspection branch filler 938
        ' inspection branch filler 939
        ' inspection branch filler 940
        ' inspection branch filler 941
        ' inspection branch filler 942
        ' inspection branch filler 943
        ' inspection branch filler 944
        ' inspection branch filler 945
        ' inspection branch filler 946
        ' inspection branch filler 947
        ' inspection branch filler 948
        ' inspection branch filler 949
        ' inspection branch filler 950
        ' inspection branch filler 951
        ' inspection branch filler 952
        ' inspection branch filler 953
        ' inspection branch filler 954
        ' inspection branch filler 955
        ' inspection branch filler 956
        ' inspection branch filler 957
        ' inspection branch filler 958
        ' inspection branch filler 959
        ' inspection branch filler 960
        ' inspection branch filler 961
        ' inspection branch filler 962
        ' inspection branch filler 963
        ' inspection branch filler 964
        ' inspection branch filler 965
        ' inspection branch filler 966
        ' inspection branch filler 967
        ' inspection branch filler 968
        ' inspection branch filler 969
        ' inspection branch filler 970
        ' inspection branch filler 971
        ' inspection branch filler 972
        ' inspection branch filler 973
        ' inspection branch filler 974
        ' inspection branch filler 975
        ' inspection branch filler 976
        ' inspection branch filler 977
        ' inspection branch filler 978
        ' inspection branch filler 979
        ' inspection branch filler 980
        ' inspection branch filler 981
        ' inspection branch filler 982
        ' inspection branch filler 983
        ' inspection branch filler 984
        ' inspection branch filler 985
        ' inspection branch filler 986
        ' inspection branch filler 987
        ' inspection branch filler 988
        ' inspection branch filler 989
        ' inspection branch filler 990
        ' inspection branch filler 991
        ' inspection branch filler 992
        ' inspection branch filler 993
        ' inspection branch filler 994
        ' inspection branch filler 995
        ' inspection branch filler 996
        ' inspection branch filler 997
        ' inspection branch filler 998
        ' inspection branch filler 999
        ' inspection branch filler 1000
        ' inspection branch filler 1001
        ' inspection branch filler 1002
        ' inspection branch filler 1003
        ' inspection branch filler 1004
        ' inspection branch filler 1005
        ' inspection branch filler 1006
        ' inspection branch filler 1007
        ' inspection branch filler 1008
        ' inspection branch filler 1009
        ' inspection branch filler 1010
        ' inspection branch filler 1011
        ' inspection branch filler 1012
        ' inspection branch filler 1013
        ' inspection branch filler 1014
        ' inspection branch filler 1015
        ' inspection branch filler 1016
        ' inspection branch filler 1017
        ' inspection branch filler 1018
        ' inspection branch filler 1019
        ' inspection branch filler 1020
        ' inspection branch filler 1021
        ' inspection branch filler 1022
        ' inspection branch filler 1023
        ' inspection branch filler 1024
        ' inspection branch filler 1025
        ' inspection branch filler 1026
        ' inspection branch filler 1027
        ' inspection branch filler 1028
        ' inspection branch filler 1029
        ' inspection branch filler 1030
        ' inspection branch filler 1031
        ' inspection branch filler 1032
        ' inspection branch filler 1033
        ' inspection branch filler 1034
        ' inspection branch filler 1035
        ' inspection branch filler 1036
        ' inspection branch filler 1037
        ' inspection branch filler 1038
        ' inspection branch filler 1039
        ' inspection branch filler 1040
        ' inspection branch filler 1041
        ' inspection branch filler 1042
        ' inspection branch filler 1043
        ' inspection branch filler 1044
        ' inspection branch filler 1045
        ' inspection branch filler 1046
        ' inspection branch filler 1047
        ' inspection branch filler 1048
        ' inspection branch filler 1049
        ' inspection branch filler 1050
        ' inspection branch filler 1051
        ' inspection branch filler 1052
        ' inspection branch filler 1053
        ' inspection branch filler 1054
        ' inspection branch filler 1055
        ' inspection branch filler 1056
        ' inspection branch filler 1057
        ' inspection branch filler 1058
        ' inspection branch filler 1059
        ' inspection branch filler 1060
        ' inspection branch filler 1061
        ' inspection branch filler 1062
        ' inspection branch filler 1063
        ' inspection branch filler 1064
        ' inspection branch filler 1065
        ' inspection branch filler 1066
        ' inspection branch filler 1067
        ' inspection branch filler 1068
        ' inspection branch filler 1069
        ' inspection branch filler 1070
        ' inspection branch filler 1071
        ' inspection branch filler 1072
        ' inspection branch filler 1073
        ' inspection branch filler 1074
        ' inspection branch filler 1075
        ' inspection branch filler 1076
        ' inspection branch filler 1077
        ' inspection branch filler 1078
        ' inspection branch filler 1079
        ' inspection branch filler 1080
        ' inspection branch filler 1081
        ' inspection branch filler 1082
        ' inspection branch filler 1083
        ' inspection branch filler 1084
        ' inspection branch filler 1085
        ' inspection branch filler 1086
        ' inspection branch filler 1087
        ' inspection branch filler 1088
        ' inspection branch filler 1089
        ' inspection branch filler 1090
        ' inspection branch filler 1091
        ' inspection branch filler 1092
        ' inspection branch filler 1093
        ' inspection branch filler 1094
        ' inspection branch filler 1095
        ' inspection branch filler 1096
        ' inspection branch filler 1097
        ' inspection branch filler 1098
        ' inspection branch filler 1099
        ' inspection branch filler 1100
        ' inspection branch filler 1101
        ' inspection branch filler 1102
        ' inspection branch filler 1103
        ' inspection branch filler 1104
        ' inspection branch filler 1105
        ' inspection branch filler 1106
        ' inspection branch filler 1107
        ' inspection branch filler 1108
        ' inspection branch filler 1109
        ' inspection branch filler 1110
        ' inspection branch filler 1111
        ' inspection branch filler 1112
        ' inspection branch filler 1113
        ' inspection branch filler 1114
        ' inspection branch filler 1115
        ' inspection branch filler 1116
        ' inspection branch filler 1117
        ' inspection branch filler 1118
        ' inspection branch filler 1119
    End Function

    Private Sub ConnectPlc(ip As String)
        Thread.Sleep(10)
        _isRunning = True
    End Sub

    Private Sub CaptureCameraImage()
        Thread.Sleep(10)
    End Sub

    Private Sub SaveRecipe()
        Dim recipePath = ConfigurationManager.AppSettings("RecipePath")
        System.IO.File.WriteAllText(recipePath & "\last.txt", DateTime.Now.ToString())
    End Sub

    Private Sub UpdateStatus(message As String)
        If Me.InvokeRequired Then
            Me.BeginInvoke(New Action(Of String)(AddressOf UpdateStatus), message)
            Return
        End If
        Me.Text = message
    End Sub
End Class